name: 'Build, Test and Publish'

on:
  push:
    branches: [ 'main' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the version from composer.json
        run: echo "VERSION=$(jq -r '.version' composer.json)" >> $GITHUB_ENV

      - name: Build app
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/app/Dockerfile
          push: true
          tags: marcostmunhoz/fiap-hackathon-monolith:${{ env.VERSION }}

  test:
    runs-on: ubuntu-latest

    needs: [ build ]

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: marcostmunhoz/fiap-hackathon-monolith:${{ env.VERSION }}
          options: --target development
          run: |
            composer analyze
            composer test:coverage

  publish:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [ build, test ]

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        run: |
          echo "Published version: ${{ env.VERSION }}"